### PR TITLE
Feat/89 login

### PR DESCRIPTION
**Pull request by vLuuk**

### CODE REVIEW

**Comment by julioandre** [comment]
Hey guys I am not able to login to either teams or my Fontys account and that's why I couldn't contact. But I sent Luuk an email tho. There are so open merge requests on my front end repo can you guys accept and merge them

**Comment by vLuuk** [comment]
already commited fixed merge conflicts

**Comment by vLuuk** [comment]
Hi Julio,

I heard that from Chris. It's fine, but we didn't hear anything from you, so that's why we were a little bit confused. I will look at your merge requests, so you can continue working on your frontend!

**Comment by julioandre** [comment]
There are open pull requests on MiAutots the other front end repo

**Comment by julioandre** [comment]
Okay thanks and please contact me on julioandre275@gmail.com and my account will be available starting tomorrow

**Pull request merged**
